 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/web_reservations", type: :request do
  # WebReservation. As you add validations to WebReservation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WebReservation.create! valid_attributes
      get web_reservations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      web_reservation = WebReservation.create! valid_attributes
      get web_reservation_url(web_reservation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_web_reservation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      web_reservation = WebReservation.create! valid_attributes
      get edit_web_reservation_url(web_reservation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WebReservation" do
        expect {
          post web_reservations_url, params: { web_reservation: valid_attributes }
        }.to change(WebReservation, :count).by(1)
      end

      it "redirects to the created web_reservation" do
        post web_reservations_url, params: { web_reservation: valid_attributes }
        expect(response).to redirect_to(web_reservation_url(WebReservation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WebReservation" do
        expect {
          post web_reservations_url, params: { web_reservation: invalid_attributes }
        }.to change(WebReservation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post web_reservations_url, params: { web_reservation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested web_reservation" do
        web_reservation = WebReservation.create! valid_attributes
        patch web_reservation_url(web_reservation), params: { web_reservation: new_attributes }
        web_reservation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the web_reservation" do
        web_reservation = WebReservation.create! valid_attributes
        patch web_reservation_url(web_reservation), params: { web_reservation: new_attributes }
        web_reservation.reload
        expect(response).to redirect_to(web_reservation_url(web_reservation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        web_reservation = WebReservation.create! valid_attributes
        patch web_reservation_url(web_reservation), params: { web_reservation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested web_reservation" do
      web_reservation = WebReservation.create! valid_attributes
      expect {
        delete web_reservation_url(web_reservation)
      }.to change(WebReservation, :count).by(-1)
    end

    it "redirects to the web_reservations list" do
      web_reservation = WebReservation.create! valid_attributes
      delete web_reservation_url(web_reservation)
      expect(response).to redirect_to(web_reservations_url)
    end
  end
end
